### ISSUE TITLE
批量下载？

### ISSUE THREAD

**Issue by Arrtime** [ColdThunder11/ChaoXingDownload#1]

**Comment by Arrtime** [comment]
请问有办法

**Comment by Arrtime** [comment]
如题 请问可以批量下载吗？

**Comment by ColdThunder11** [comment]
这个可以考虑做一下，但是一次下载多个文件的行为可能会被浏览器阻止
你是要勾选要下载的下载还是整课里面的内容一起下载，应该东西也不会很多的吧

**Comment by Arrtime** [comment]
> 这个可以考虑做一下，但是一次下载多个文件的行为可能会被浏览器阻止
> 你是要勾选要下载的下载还是整课里面的内容一起下载，应该东西也不会很多的吧

主要是批量下载视频。我找了找，都没有方法，对于不太懂这些的小白还是比较需要的。而且其实单个视频下载方法比较多了吧，如果做好批量下载可以帮助更多人。（当然也看作者的时间与兴趣了）

**Comment by ColdThunder11** [comment]
我感觉这个需求也不大，毕竟视频也不会特别多，多点一下也花不了太多时间
（其实写这个主要是拿来下ppt的，其他的都是附赠的 ）

**Comment by ColdThunder11** [comment]
> > 这个可以考虑做一下，但是一次下载多个文件的行为可能会被浏览器阻止
> > 你是要勾选要下载的下载还是整课里面的内容一起下载，应该东西也不会很多的吧
> 
> 主要是批量下载视频。我找了找，都没有方法，对于不太懂这些的小白还是比较需要的。而且其实单个视频下载方法比较多了吧，如果做好批量下载可以帮助更多人。（当然也看作者的时间与兴趣了）

现在已经可以一次下载整节课里的所有内容了

**Comment by Arrtime** [comment]
我更新后试了试 好像没找到可以批量下载整个课程的按钮呀 只可以单个视频下载

**Comment by ColdThunder11** [comment]
[截图](https://onedrive.coldthunder11.workers.dev/?file=/static/images/Annotation 2020-04-01 082515.jpg)
在课程主页面的最上面，如果没有请带上控制台的错误和当前页面的html反馈给我来修复

**Comment by ColdThunder11** [comment]
[截图](https://onedrive.coldthunder11.workers.dev/?file=/static/images/Annotation%202020-04-01%20082515.jpg)
在课程主页面的最上面，如果没有请带上控制台的错误和当前页面的html反馈给我来修复

**Comment by Arrtime** [comment]
你好 是你截图这样的 只是可以下载课程的全部内容吗 这个脚本下载的只是下载一节的课件吧
