### ISSUE TITLE
整节课批量下载

### ISSUE THREAD

**Issue by ChurchillDu** [ColdThunder11/ChaoXingDownload#11]
怎么整节课资源批量下载呢？我没有找到相应的button

**Comment by copurxia** [comment]
看了下被隐藏了，一个包含ct11_dl class 的div

**Comment by ocean0117** [comment]
> 看了下被隐藏了，一个包含ct11_dl class 的div

那么应该怎么显示出来呢？是故意隐藏的？

**Comment by ColdThunder11** [comment]
> > 看了下被隐藏了，一个包含ct11_dl class 的div
> 
> 那么应该怎么显示出来呢？是故意隐藏的？

是学习通的检测，既然还有人有需求我就更新了下，下载最新版本就行了
