### ISSUE TITLE
新课程不支持

### ISSUE THREAD

**Issue by ZhaoAni** [ColdThunder11/ChaoXingDownload#14]
不只是什么原因，脚本在旧课程页面上完美运行，在新课程界面上无法运行

**Comment by ZhaoAni** [comment]
以“i.mooc.chaoxing.com”和“mooc1-1.chaoxing.com”为前缀的网站上能够正常运行。
其他前缀例如“mooc1.chaoxing.com”的网站上脚本无法运行。

**Comment by ColdThunder11** [comment]
> 以“i.mooc.chaoxing.com”和“mooc1-1.chaoxing.com”为前缀的网站上能够正常运行。 其他前缀例如“mooc1.chaoxing.com”的网站上脚本无法运行。

我这里mooc1前缀的新版课程页面没问题，我也无法获取足够的信息定位你的问题，如果你不介意的话需要发送超星账号到我的邮箱lslyj27761@gmail.com我才能帮忙定位解决问题。

**Comment by ZhaoAni** [comment]
> > 以“i.mooc.chaoxing.com”和“mooc1-1.chaoxing.com”为前缀的网站上能够正常运行。 其他前缀例如“mooc1.chaoxing.com”的网站上脚本无法运行。
> 
> 我这里mooc1前缀的新版课程页面没问题，我也无法获取足够的信息定位你的问题，如果你不介意的话需要发送超星账号到我的邮箱[lslyj27761@gmail.com](mailto:lslyj27761@gmail.com)我才能帮忙定位解决问题。

您好，我尝试了一下已经没有问题了😂。脚本运行的很完美，之前应该是我这边操作有毛病，不好意思哈哈哈。
