### ISSUE TITLE
{"error":"rejected ip:你的ip地址"}

### ISSUE THREAD

**Issue by SlaynXQ** [ColdThunder11/ChaoXingDownload#21]

**Comment by ColdThunder11** [comment]
原接口已经不可用，如果没有其它办法那文档类型的只能通过学习通的WebOffice接口保存为PDF或者图片了，获得原始文件不大可能，~~除非有大佬救一救~~。
保存为PDF的功能经验证可以实现，要脚本添加的话等下周什么时候有空再研究怎么弄了。

**Comment by SlaynXQ** [comment]
:disappointed_relieved:

[这个项目](https://github.com/PyJun/Mooc_Downloader)获取的office文件好像还是原始的，但是视频

**Comment by SlaynXQ** [comment]
> 原接口已经不可用，如果没有其它办法那文档类型的只能通过学习通的WebOffice接口保存为PDF或者图片了，获得原始文件不大可能，~除非有大佬救一救~。 保存为PDF的功能经验证可以实现，要脚本添加的话等下周什么时候有空再研究怎么弄了。


大佬加油
😥之前好几个月能方便学习都得感谢你
[这个项目](https://github.com/PyJun/Mooc_Downloader)获取的office文件好像还是原始的，但是视频的话暂时没有方法

**Comment by ColdThunder11** [comment]
> 大佬加油 😥之前好几个月能方便学习都得感谢你 [这个项目](https://github.com/PyJun/Mooc_Downloader)获取的office文件好像还是原始的，但是视频的话暂时没有方法

视频的话临时push了一个版本，点击下载以后会跳转到视频的标签页右键选择视频另存为应该是可以下载的，你试试

**Comment by ColdThunder11** [comment]
> 大佬加油 😥之前好几个月能方便学习都得感谢你 [这个项目](https://github.com/PyJun/Mooc_Downloader)获取的office文件好像还是原始的，但是视频的话暂时没有方法

文档类型也是有办法下载的但是通过油猴脚本的方法可能不太好实现，需要研究下

**Comment by SlaynXQ** [comment]
谢谢！

> > 大佬加油 😥之前好几个月能方便学习都得感谢你 [这个项目](https://github.com/PyJun/Mooc_Downloader)获取的office文件好像还是原始的，但是视频的话暂时没有方法
> 
> 视频的话临时push了一个版本，点击下载以后会跳转到视频的标签页右键选择视频另存为应该是可以下载的，你试试，不过视频名称没了

谢谢！好的
