### ISSUE TITLE
失败，已被禁止

### ISSUE THREAD

**Issue by xianerhello** [ColdThunder11/ChaoXingDownload#26]
下载不了
![20220906_111129](https://user-images.githubusercontent.com/32446697/188539484-95f15556-7b71-4200-a9a8-68eebc11ffd8.jpg)

**Comment by ColdThunder11** [comment]
> 下载不了 ![20220906_111129](https://user-images.githubusercontent.com/32446697/188539484-95f15556-7b71-4200-a9a8-68eebc11ffd8.jpg)

是不是通过http访问的，是的话尝试改成https

**Comment by xianerhello** [comment]
> > 下载不了 ![20220906_111129](https://user-images.githubusercontent.com/32446697/188539484-95f15556-7b71-4200-a9a8-68eebc11ffd8.jpg)
> 
> 是不是通过http访问的，是的话尝试改成https

你好，我看了，是通过https访问的

是xdown的问题，扩展关闭后就可以了，谢谢了

![20220907_085751](https://user-images.githubusercontent.com/32446697/188765632-5e280ad6-5334-42b2-a2be-eac5231774b2.jpg)
