### ISSUE TITLE
显示403

### ISSUE THREAD

**Issue by liyize010215** [ColdThunder11/ChaoXingDownload#4]
>_< 很抱歉，您没有权限访问这个页面！ (403)
40.74.123.205
mango-download-service-2190698592-dsgs6

**Comment by renjianfenmu** [comment]
脚本中objectid换成https://cs-ans.chaoxing.com/download/

**Comment by ColdThunder11** [comment]
> 脚本中objectid换成https://cs-ans.chaoxing.com/download/

这几天忙没看邮箱没注意，感谢提醒，现在已经修改了
