### ISSUE TITLE
a标签的样式会被加入display: none;导致插件失效

### ISSUE THREAD

**Issue by panghaibin** [ColdThunder11/ChaoXingDownload#6]
目前超星的课程学习页面会对a标签的样式加入display: none;导致插件无法工作
![1](https://user-images.githubusercontent.com/63835145/113465576-a96d7f80-9467-11eb-8bba-884bfadffef1.gif)

通过打断点发现该行为的js代码位于 https://mooc1-1.chaoxing.com/js/courselist/jquery-1.7.2.min.js 
![Snipaste_2021-04-03_10-33-16](https://user-images.githubusercontent.com/63835145/113465649-5942ed00-9468-11eb-9360-1b4688e595ea.jpg)

目前我想到的解决方法是将注入A标签的行为改为P标签，让用户自行复制下载链接打开下载，自然这样就无法实现批量下载了
```
......
var downloadTag = document.createElement("P");
//downloadTag.setAttribute("href","https://cs-ans.chaoxing.com/download/"+jsondata.objectid);
downloadTag.innerHTML=jsondata.name+" 的下载链接：<br> https://cs-ans.chaoxing.com/download/"+jsondata.objectid;
......
```

有没有更好的解决方法？

**Comment by ColdThunder11** [comment]
> 目前超星的课程学习页面会对a标签的样式加入display: none;导致插件无法工作
> ![1](https://user-images.githubusercontent.com/63835145/113465576-a96d7f80-9467-11eb-8bba-884bfadffef1.gif)
> 
> 通过打断点发现该行为的js代码位于 https://mooc1-1.chaoxing.com/js/courselist/jquery-1.7.2.min.js
> ![Snipaste_2021-04-03_10-33-16](https://user-images.githubusercontent.com/63835145/113465649-5942ed00-9468-11eb-9360-1b4688e595ea.jpg)
> 
> 目前我想到的解决方法是将注入A标签的行为改为P标签，让用户自行复制下载链接打开下载，自然这样就无法实现批量下载了
> 
> ```
> ......
> var downloadTag = document.createElement("P");
> //downloadTag.setAttribute("href","https://cs-ans.chaoxing.com/download/"+jsondata.objectid);
> downloadTag.innerHTML=jsondata.name+" 的下载链接：<br> https://cs-ans.chaoxing.com/download/"+jsondata.objectid;
> ......
> ```
> 
> 有没有更好的解决方法？

统一使用div和js来下载了
