### ISSUE TITLE
显示不了标签

### ISSUE THREAD

**Issue by theskysmiles** [ColdThunder11/ChaoXingDownload#9]
前几天还能通过点击PPT左上角的标签进行下载，今天试了一下，不知为何不行了
重启浏览器几遍也不行，标签消失了

**Comment by ColdThunder11** [comment]
> 前几天还能通过点击PPT左上角的标签进行下载，今天试了一下，不知为何不行了
> 重启浏览器几遍也不行，标签消失了

检测又改了，已经修复单个下载，整节课我懒得去找哪里检测了，捉迷藏真不好玩
